language: php

php:
  - 5.6
  - 7

services:
  - redis-server

  - phpenv config-rm xdebug.ini

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev

script:
  - ./vendor/bin/phpunit tests/